# Generated by Django 3.1.6 on 2021-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
                ('single_price', models.IntegerField()),
                ('multiple_price', models.IntegerField()),
                ('extended_price', models.IntegerField()),
                ('compatibility', models.CharField(blank=True, max_length=50)),
                ('version', models.DecimalField(decimal_places=2, max_digits=3)),
                ('browser_support', models.CharField(blank=True, max_length=225)),
                ('layout', models.CharField(blank=True, max_length=50)),
                ('css_type', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('1', 'Ecommerce'), ('2', 'Digital Agency'), ('3', 'Other')], max_length=50)),
                ('topic', models.CharField(choices=[('1', 'General'), ('2', 'Entreprneurs'), ('3', 'Other')], max_length=50)),
                ('tags', models.TextField()),
                ('description', models.TextField()),
                ('link', models.CharField(blank=True, max_length=225)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('zipfile', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
