# Generated by Django 3.1.6 on 2021-11-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211127_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatibility',
            field=models.CharField(blank=True, default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, default='https://devfreak1.000webhostapp.com', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='zipfile',
            field=models.FileField(default=None, upload_to='uploads'),
        ),
    ]
