# Generated by Django 3.1.6 on 2021-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211130_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gateway',
            field=models.CharField(default='paddle', max_length=50),
        ),
    ]
