# Generated by Django 3.1.6 on 2021-12-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.CharField(default='sdsds', max_length=100),
            preserve_default=False,
        ),
    ]
