# Generated by Django 3.1.6 on 2021-12-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('pending', 'pending'), ('removed', 'removed')], default='pending', max_length=50),
        ),
    ]
