# Generated by Django 3.1.6 on 2021-12-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211206_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=224)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('cancelled', 'cancelled')], max_length=50)),
                ('dtime', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product')),
            ],
        ),
    ]
