# Generated by Django 3.1.6 on 2021-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('reversed', 'reversed'), ('on-hold', 'on-hold'), ('cancelled', 'cancelled')], max_length=50),
        ),
    ]
