# Generated by Django 3.1.6 on 2021-12-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211207_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
