# Generated by Django 3.1.6 on 2021-12-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_id',
            field=models.CharField(default=5, max_length=224),
            preserve_default=False,
        ),
    ]
