# Generated by Django 3.1.6 on 2021-12-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211207_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exlusive',
            field=models.IntegerField(default=0),
        ),
    ]
