# Generated by Django 3.1.6 on 2022-01-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product_list_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
                ('order_id', models.CharField(max_length=224)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
