# Generated by Django 3.1.6 on 2022-01-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_purchaseditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('dtime', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
                ('dtime', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.RemoveField(
            model_name='order',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='mireka@sds.sds', max_length=224),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=12121),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_url',
            field=models.TextField(default='sdsds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.CharField(default='232', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(max_length=10),
        ),
    ]
