# Generated by Django 3.1.6 on 2022-01-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220109_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
    ]
