# Generated by Django 3.1.6 on 2022-01-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20220109_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='processed', max_length=50),
        ),
    ]
