# Generated by Django 3.1.6 on 2022-01-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
