# Generated by Django 3.0.5 on 2022-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('pending', 'pending'), ('removed', 'removed')], max_length=50),
        ),
    ]
