# Generated by Django 3.0.5 on 2022-01-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220113_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
