# Generated by Django 3.0.5 on 2022-01-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
